'use client';

import { useEffect, useMemo, useState } from 'react';
import { keccak256, stringToBytes, type Hex } from 'viem';

interface Props {
  txHash: Hex;
  reasonHash: Hex;
}

type CacheEntry = { canonicalJson: string };

const STORAGE_PREFIX = 'neutrino:decision:';

function readCache(txHash: Hex): CacheEntry | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = window.localStorage.getItem(`${STORAGE_PREFIX}${txHash.toLowerCase()}`);
    if (!raw) return null;
    return JSON.parse(raw) as CacheEntry;
  } catch {
    return null;
  }
}

export function DecisionVerifier({ txHash, reasonHash }: Props) {
  const [cache, setCache] = useState<CacheEntry | null>(null);
  const [verified, setVerified] = useState<null | 'ok' | 'mismatch'>(null);
  const [showJson, setShowJson] = useState(false);

  useEffect(() => {
    setCache(readCache(txHash));
  }, [txHash]);

  const recomputed: Hex | null = useMemo(() => {
    if (!cache) return null;
    return keccak256(stringToBytes(cache.canonicalJson));
  }, [cache]);

  function verify() {
    if (!recomputed) return;
    setVerified(recomputed.toLowerCase() === reasonHash.toLowerCase() ? 'ok' : 'mismatch');
  }

  if (!cache) {
    return (
      <section className="rounded-lg border border-dashed border-zinc-300 bg-white p-6">
        <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          Decision receipt
        </p>
        <p className="mt-2 text-sm font-medium text-zinc-900">
          Canonical payload not in this browser&apos;s cache
        </p>
        <p className="mt-1 text-sm text-zinc-600">
          The full audit JSON for this decision is generated by{' '}
          <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs">/api/run-agent</code> and stored
          locally per browser. To populate it for this decision, trigger a new run from the home page —
          or in production, this would be IPFS-pinned and globally retrievable by reasonHash.
        </p>
        <p className="mt-3 font-mono text-xs text-zinc-500">
          On-chain reasonHash: <span className="text-zinc-700">{reasonHash}</span>
        </p>
      </section>
    );
  }

  return (
    <section className="rounded-lg border border-zinc-200 bg-white p-6">
      <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1">
        <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          Decision receipt — verifiable
        </p>
        <p className="text-xs text-zinc-500">
          schema <code className="rounded bg-zinc-100 px-1 py-0.5">neutrino.decision.v1</code>
        </p>
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={verify}
          className="inline-flex h-9 items-center rounded-md bg-zinc-950 px-3 text-sm font-medium text-white hover:bg-zinc-800"
        >
          Verify hash
        </button>
        {verified === 'ok' ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-0.5 text-xs font-medium text-emerald-700 ring-1 ring-inset ring-emerald-200">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
            keccak256(payload) matches on-chain reasonHash
          </span>
        ) : null}
        {verified === 'mismatch' ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-2.5 py-0.5 text-xs font-medium text-rose-700 ring-1 ring-inset ring-rose-200">
            <span className="h-1.5 w-1.5 rounded-full bg-rose-500" />
            mismatch — payload not authentic
          </span>
        ) : null}
        <button
          type="button"
          onClick={() => setShowJson((v) => !v)}
          className="inline-flex h-9 items-center rounded-md border border-zinc-300 bg-white px-3 text-sm text-zinc-700 hover:bg-zinc-50"
        >
          {showJson ? 'Hide JSON' : 'View JSON'}
        </button>
      </div>

      <dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2">
        <div>
          <dt className="font-medium uppercase tracking-wider text-zinc-500">On-chain reasonHash</dt>
          <dd className="mt-1 break-all font-mono text-zinc-700">{reasonHash}</dd>
        </div>
        <div>
          <dt className="font-medium uppercase tracking-wider text-zinc-500">
            Recomputed from local payload
          </dt>
          <dd className="mt-1 break-all font-mono text-zinc-700">{recomputed ?? '—'}</dd>
        </div>
      </dl>

      {showJson ? (
        <pre className="mt-4 max-h-96 overflow-auto rounded-md border border-zinc-200 bg-zinc-50 p-4 text-xs leading-relaxed text-zinc-800">
          {prettyJson(cache.canonicalJson)}
        </pre>
      ) : null}

      <p className="mt-4 text-xs text-zinc-500">
        The JSON above is byte-stable. Re-hash it client-side with{' '}
        <code className="rounded bg-zinc-100 px-1 py-0.5">keccak256</code> and you get the same
        bytes32 emitted by{' '}
        <code className="rounded bg-zinc-100 px-1 py-0.5">RWADecisionLogger.DecisionLogged.reasonHash</code>.
      </p>
    </section>
  );
}

function prettyJson(json: string): string {
  try {
    return JSON.stringify(JSON.parse(json), null, 2);
  } catch {
    return json;
  }
}
