"use client";

import { useEffect, useMemo, useState } from "react";
import { keccak256, stringToBytes, type Hex } from "viem";

interface Props {
  txHash: Hex;
  reasonHash: Hex;
}

type CacheEntry = { canonicalJson: string };
type SourceState = "live" | "stub" | "simulated" | "n/a";

interface ParsedDecision {
  asset: {
    symbol: string;
    kind: string;
    reference: string | null;
    market: string | null;
  };
  sources: Record<string, SourceState>;
  snapshot: Record<string, string | number | boolean | null>;
  breakdown: { total: number };
  policy: {
    name: string;
    blockAfterHoursEquity: boolean;
    maxRiskForAllocate: number;
    fallbackYieldAsset: string;
  };
  action: string;
  riskScore: number;
  reason: string;
  xstocks?: {
    indicativePriceUsd: number | null;
    priceSource: string | null;
    marketTradingHalted: boolean | null;
    atomicTradingHalted: boolean | null;
  } | null;
  narration: {
    model: string | null;
    fromLlm: boolean;
  };
}

const STORAGE_PREFIX = "neutrino:decision:";

function readCache(txHash: Hex): CacheEntry | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(
      `${STORAGE_PREFIX}${txHash.toLowerCase()}`,
    );
    if (!raw) return null;
    return JSON.parse(raw) as CacheEntry;
  } catch {
    return null;
  }
}

export function DecisionVerifier({ txHash, reasonHash }: Props) {
  const [cache, setCache] = useState<CacheEntry | null>(null);
  const [verified, setVerified] = useState<null | "ok" | "mismatch">(null);
  const [showJson, setShowJson] = useState(false);

  useEffect(() => {
    queueMicrotask(() => setCache(readCache(txHash)));
  }, [txHash]);

  const recomputed: Hex | null = useMemo(() => {
    if (!cache) return null;
    return keccak256(stringToBytes(cache.canonicalJson));
  }, [cache]);

  const parsed = useMemo(() => {
    if (!cache) return null;
    try {
      return JSON.parse(cache.canonicalJson) as ParsedDecision;
    } catch {
      return null;
    }
  }, [cache]);

  function verify() {
    if (!recomputed) return;
    setVerified(
      recomputed.toLowerCase() === reasonHash.toLowerCase() ? "ok" : "mismatch",
    );
  }

  if (!cache) {
    return (
      <section className="rounded-lg border border-dashed border-zinc-300 bg-white p-6">
        <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          Decision receipt
        </p>
        <p className="mt-2 text-sm font-medium text-zinc-900">
          Canonical payload not in this browser&apos;s cache
        </p>
        <p className="mt-1 text-sm text-zinc-600">
          The full audit JSON for this decision is generated by{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs">
            /api/run-agent
          </code>{" "}
          and stored locally per browser. To populate it for this decision,
          trigger a new run from the home page — or in production, this would be
          IPFS-pinned and globally retrievable by reasonHash.
        </p>
        <p className="mt-3 font-mono text-xs text-zinc-500">
          On-chain reasonHash:{" "}
          <span className="text-zinc-700">{reasonHash}</span>
        </p>
      </section>
    );
  }

  return (
    <section className="rounded-lg border border-zinc-200 bg-white p-6">
      <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1">
        <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          Decision receipt — verifiable
        </p>
        <p className="text-xs text-zinc-500">
          schema{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5">
            neutrino.decision.v2
          </code>
        </p>
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={verify}
          className="inline-flex h-9 items-center rounded-md bg-zinc-950 px-3 text-sm font-medium text-white hover:bg-zinc-800"
        >
          Verify hash
        </button>
        {verified === "ok" ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-0.5 text-xs font-medium text-emerald-700 ring-1 ring-inset ring-emerald-200">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
            keccak256(payload) matches on-chain reasonHash
          </span>
        ) : null}
        {verified === "mismatch" ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-2.5 py-0.5 text-xs font-medium text-rose-700 ring-1 ring-inset ring-rose-200">
            <span className="h-1.5 w-1.5 rounded-full bg-rose-500" />
            mismatch — payload not authentic
          </span>
        ) : null}
        <button
          type="button"
          onClick={() => setShowJson((v) => !v)}
          className="inline-flex h-9 items-center rounded-md border border-zinc-300 bg-white px-3 text-sm text-zinc-700 hover:bg-zinc-50"
        >
          {showJson ? "Hide JSON" : "View JSON"}
        </button>
      </div>

      <dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2">
        <div>
          <dt className="font-medium uppercase tracking-wider text-zinc-500">
            On-chain reasonHash
          </dt>
          <dd className="mt-1 break-all font-mono text-zinc-700">
            {reasonHash}
          </dd>
        </div>
        <div>
          <dt className="font-medium uppercase tracking-wider text-zinc-500">
            Recomputed from local payload
          </dt>
          <dd className="mt-1 break-all font-mono text-zinc-700">
            {recomputed ?? "—"}
          </dd>
        </div>
      </dl>

      {parsed ? <ParsedReceiptSummary decision={parsed} /> : null}

      {showJson ? (
        <pre className="mt-4 max-h-96 overflow-auto rounded-md border border-zinc-200 bg-zinc-50 p-4 text-xs leading-relaxed text-zinc-800">
          {prettyJson(cache.canonicalJson)}
        </pre>
      ) : null}

      <p className="mt-4 text-xs text-zinc-500">
        The JSON above is byte-stable. Re-hash it client-side with{" "}
        <code className="rounded bg-zinc-100 px-1 py-0.5">keccak256</code> and
        you get the same bytes32 emitted by{" "}
        <code className="rounded bg-zinc-100 px-1 py-0.5">
          RWADecisionLogger.DecisionLogged.reasonHash
        </code>
        .
      </p>
    </section>
  );
}

function ParsedReceiptSummary({ decision }: { decision: ParsedDecision }) {
  return (
    <div className="mt-5 space-y-4">
      <div className="rounded-lg border border-zinc-200 bg-zinc-50 p-4">
        <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1">
          <p className="text-sm font-semibold text-zinc-950">
            {decision.asset.symbol} · {decision.action} · {decision.riskScore}
            /1000
          </p>
          <p className="text-xs text-zinc-500">
            {decision.asset.kind}
            {decision.asset.reference
              ? ` · references ${decision.asset.reference}`
              : ""}
            {decision.asset.market ? ` · ${decision.asset.market}` : ""}
          </p>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-zinc-600">
          {decision.reason}
        </p>
      </div>

      <div>
        <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
          Source status
        </p>
        <div className="mt-2 flex flex-wrap gap-2">
          {Object.entries(decision.sources).map(([label, state]) => (
            <SourceBadge key={label} label={label} state={state} />
          ))}
        </div>
      </div>

      {decision.xstocks ? (
        <div>
          <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
            xStocks public API (live read-only)
          </p>
          <div className="mt-2 grid gap-3 text-xs sm:grid-cols-3">
            <AuditCard
              title="xStocks data"
              rows={[
                [
                  "indicativePriceUsd",
                  String(decision.xstocks.indicativePriceUsd ?? "n/a"),
                ],
                ["priceSource", decision.xstocks.priceSource ?? "unavailable"],
                [
                  "marketTradingHalted",
                  String(decision.xstocks.marketTradingHalted ?? "n/a"),
                ],
                [
                  "atomicTradingHalted",
                  String(decision.xstocks.atomicTradingHalted ?? "n/a"),
                ],
              ]}
            />
          </div>
        </div>
      ) : null}

      <div className="grid gap-3 text-xs sm:grid-cols-3">
        <AuditCard
          title="Snapshot (price live · microstructure modelled)"
          rows={[
            ["onChainPrice", String(decision.snapshot.onChainPrice ?? "n/a")],
            [
              "referencePrice",
              String(decision.snapshot.referencePrice ?? "n/a"),
            ],
            ["spreadBps*", String(decision.snapshot.spreadBps ?? "n/a")],
            ["volume24hUsd*", String(decision.snapshot.volume24hUsd ?? "n/a")],
            ["marketOpen", String(decision.snapshot.marketOpen ?? "n/a")],
          ]}
        />
        <AuditCard
          title="Policy"
          rows={[
            ["name", decision.policy.name],
            ["blockAfterHours", String(decision.policy.blockAfterHoursEquity)],
            ["maxAllocateRisk", String(decision.policy.maxRiskForAllocate)],
            ["fallback", decision.policy.fallbackYieldAsset],
          ]}
        />
        <AuditCard
          title="Control"
          rows={[
            ["riskTotal", String(decision.breakdown.total)],
            ["llmModel", decision.narration.model ?? "none"],
            ["llmControlsAction", "false"],
            ["hashCovers", "full payload"],
          ]}
        />
      </div>

      <p className="text-[11px] leading-relaxed text-zinc-500">
        * <code className="rounded bg-zinc-100 px-1">spreadBps</code> and{" "}
        <code className="rounded bg-zinc-100 px-1">volume24hUsd</code> are
        modelled — the xStocks public API exposes the indicative price and
        trading status (shown above as live), not order-book microstructure.
        Every field here is covered by the on-chain{" "}
        <code className="rounded bg-zinc-100 px-1">reasonHash</code>.
      </p>
    </div>
  );
}

function SourceBadge({ label, state }: { label: string; state: SourceState }) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ring-inset ${stateClasses(state)}`}
    >
      <span className={`h-1.5 w-1.5 rounded-full ${stateDotClass(state)}`} />
      {label}: {state}
    </span>
  );
}

function AuditCard({
  title,
  rows,
}: {
  title: string;
  rows: Array<[string, string]>;
}) {
  return (
    <div className="rounded-lg border border-zinc-200 bg-white p-4">
      <p className="font-medium uppercase tracking-wider text-zinc-500">
        {title}
      </p>
      <dl className="mt-2 space-y-1">
        {rows.map(([label, value]) => (
          <div key={label} className="flex justify-between gap-3">
            <dt className="text-zinc-500">{label}</dt>
            <dd className="break-all text-right font-mono text-zinc-700">
              {value}
            </dd>
          </div>
        ))}
      </dl>
    </div>
  );
}

function stateClasses(state: SourceState): string {
  switch (state) {
    case "live":
      return "bg-emerald-50 text-emerald-700 ring-emerald-200";
    case "stub":
      return "bg-amber-50 text-amber-800 ring-amber-200";
    case "simulated":
      return "bg-violet-50 text-violet-700 ring-violet-200";
    case "n/a":
    default:
      return "bg-zinc-100 text-zinc-600 ring-zinc-200";
  }
}

function stateDotClass(state: SourceState): string {
  switch (state) {
    case "live":
      return "bg-emerald-500";
    case "stub":
      return "bg-amber-500";
    case "simulated":
      return "bg-violet-500";
    case "n/a":
    default:
      return "bg-zinc-400";
  }
}

function prettyJson(json: string): string {
  try {
    return JSON.stringify(JSON.parse(json), null, 2);
  } catch {
    return json;
  }
}
